### ISSUE TITLE
I would like to fix this 

### ISSUE THREAD

**Issue by siddhi-244** [Eduhub-Community/Eduhub#13]
**Describe the bug**
The button transition is not looking good.

**Screenshots**

https://user-images.githubusercontent.com/69195262/125196027-e1117200-e275-11eb-8cea-6ad5a05e10b8.mp4

**Desktop (please complete the following information):**
 - os : Windows [e.g. ]
 - Browser chrome  [e.g. chrome, safari]

**Smartphone (please complete the following information):**
 - Device: Samsung m51 [e.g. iPhone6]
 - OS: android  [e.g. iOS8.1]
 - Browser  chrome [e.g. stock browser, safari]

**Additional context**

**Comment by xyrelljoi** [comment]
Hi @siddhi-244 yeah sure! go ahead! we'll assign you on this😊

**Comment by siddhi-244** [comment]
Thank you!😊
