### ISSUE TITLE
Duplicate links

### ISSUE THREAD

**Issue by xyrelljoi** [Eduhub-Community/Eduhub#2]
Hi, I noticed that there are duplicated links below the website.
The `youtube channel link` and `youtube`
I think it would be better if
-  remove `youtube channel link`
- Make the `social media` font in bold
- and put the social media links under the address, i guess? (to make it more aligned)

![image](https://user-images.githubusercontent.com/77091115/124909942-9ac1d600-e01d-11eb-986e-216ba5b58102.png)

and also here:

![image](https://user-images.githubusercontent.com/77091115/124914821-63562800-e023-11eb-897e-6c4503361b3c.png)

**Comment by xyrelljoi** [comment]
if you allow me, I would like to address this issue to contribute 😄

**Comment by SahityaRoy** [comment]
> if you allow me, I would like to address this issue to contribute 😄

Yes @xyrelljoi  please remove that link

**Comment by xyrelljoi** [comment]
Thank you! I already did pr @SahityaRoy
