### ISSUE TITLE
site is small on the mobile screen

### ISSUE THREAD

**Issue by xyrelljoi** [Eduhub-Community/Eduhub#24]
**Describe the bug**
The site does not fit on the mobile screen

**To Reproduce**
1. Load the site https://eduhub-community.github.io/Eduhub/ via your phone's browser
3. Pinch the screen
4. See error on the right corner of the screen

**Expected behavior**
The site should be fit in different mobile/browser screens.

**Screenshots**
![Screenshot_2021-07-27-16-02-54-48_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/77091115/127119453-a7ef9781-ec49-4fa8-8bff-f1a3f6e07bd7.jpg)

**Smartphone (please complete the following information):**
 - Device: Oppo F9
 - OS: Android 10
 - Browser: Brave/Chromium Browser
 - Version: 1.24.85

**Additional context**
I can't fix this issue right now.

**Comment by bLaCkwEw** [comment]
Hi! I just oppened a pull request (#25) which fixes the issue.
