### ISSUE TITLE
Uploading Images of Founder and Co-Founder

### ISSUE THREAD

**Issue by Subhradeep10** [Eduhub-Community/Eduhub#6]
Profile pic of Founder and Co-Founder is always needed , whenever we start any organization

![image](https://user-images.githubusercontent.com/70656957/125150866-9a7e2380-e160-11eb-9014-a90764e57172.png)

![image](https://user-images.githubusercontent.com/70656957/125150874-a7027c00-e160-11eb-9471-eb2dc3818b6c.png)

**Comment by xyrelljoi** [comment]
way to go @Subhradeep10! would you like to be assigned in this?

**Comment by Subhradeep10** [comment]
@xyrelljoi Yes , I will give me best

**Comment by SahityaRoy** [comment]
@Subhradeep10 you can upload picture

**Comment by deeqakkk** [comment]
I can fix this if this issue is still there.

**Comment by xyrelljoi** [comment]
hi @deeqakkk  sure! please do fix it ☺️
