### ISSUE TITLE
Misaligned text at the front page

### ISSUE THREAD

**Issue by xyrelljoi** [Eduhub-Community/Eduhub#7]
**Describe the bug**
There is misalignment in the front page and needs fixing.

**To reproduce**
**Steps to reproduce the behavior**
1. Use a mobile device.
2. Visit the website and go the main page.
**Expected behavior**
I think it would be better if the texts are centered.

**Screenshots**
From the mobile.
![Screenshot_2021-07-10-04-54-48-72_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/77091115/125136241-08b0ef00-e13d-11eb-9057-2636a6f0a97e.jpg)

**Comment by PhilsKay** [comment]
Yes that's true.

**Comment by SahityaRoy** [comment]
> **Describe the bug**
> There is misalignment in the front page and needs fixing.
> 
> **To reproduce**
> **Steps to reproduce the behavior**
> 
> 1. Use a mobile device.
> 2. Visit the website and go the main page.
>    **Expected behavior**
>    I think it would be better if the texts are centered.
> 
> **Screenshots**
> From the mobile.
> ![Screenshot_2021-07-10-04-54-48-72_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/77091115/125136241-08b0ef00-e13d-11eb-9057-2636a6f0a97e.jpg)

Yeah @xyrelljoi  if you can solve this issue please go ahead with this issue
