### ISSUE TITLE
The red color of navbar is looking bad! I WOULD like to redesign navbar with hover and active effects 

### ISSUE THREAD

**Issue by siddhi-244** [Eduhub-Community/Eduhub#8]

**Comment by xyrelljoi** [comment]
can you give me a screenshot?

**Comment by siddhi-244** [comment]
Yes wait

**Comment by siddhi-244** [comment]
![Screenshot_20210710-131249_Chrome](https://user-images.githubusercontent.com/69195262/125155961-9104b380-e180-11eb-955f-d57911b98713.jpg)
@xyrelljoi

**Comment by xyrelljoi** [comment]
let's wait @SahityaRoy for you to assigned ☺️

**Comment by siddhi-244** [comment]
Sure !

**Comment by SahityaRoy** [comment]
> Sure !

@siddhi-244  yes please change this because its not looking good .
